var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/institution/(portal)/competitors/[competitorId]/lifecycle/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1j2-mtl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1hkrv0u.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_institution_layout_tsx_1ql3u_2._.js")
R.c("server/chunks/ssr/_1t328kr._.js")
R.c("server/chunks/ssr/0ivl_institution_(portal)_competitors_[competitorId]_lifecycle_page_actions_0m7jte9.js")
R.m(11923)
module.exports=R.m(11923).exports
