var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/competitions/[id]/zones/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1q13p8j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cfsyn2.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_134j8s0._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_competitions_[id]_zones_page_actions_0e_r_mm.js")
R.m(91550)
module.exports=R.m(91550).exports
