var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/competitor/(portal)/competitions/[competitionId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fod921._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0mnmvsx.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_competitor_layout_tsx_1e-x7vm._.js")
R.c("server/chunks/ssr/_1cmd3nr._.js")
R.c("server/chunks/ssr/1jng_app_competitor_(portal)_competitions_[competitionId]_page_actions_0ehy2nz.js")
R.m(32154)
module.exports=R.m(32154).exports
