var R=require("../../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/competitions/[id]/skills/[skillId]/pathway/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zupwap._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_013phkz.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_134j8s0._.js")
R.c("server/chunks/ssr/1jng_app_admin_competitions_[id]_skills_[skillId]_pathway_page_actions_1i-vtlw.js")
R.m(53651)
module.exports=R.m(53651).exports
