// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/accept-invite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accept-invite">> = Specific
  const handler = {} as typeof import("../../app/accept-invite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/account/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account/change-password">> = Specific
  const handler = {} as typeof import("../../app/account/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/age-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/age-rules">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/age-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/appeals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/appeals">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/appeals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/assignments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/assignments">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/assignments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/competitors/[competitorId]/eligibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/competitors/[competitorId]/eligibility">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/competitors/[competitorId]/eligibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/competitors/[competitorId]/lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/competitors/[competitorId]/lifecycle">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/competitors/[competitorId]/lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/marking-schemes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/marking-schemes">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/marking-schemes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/nominations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/nominations">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/nominations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/pathways/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/pathways">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/pathways/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/results">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/schedule">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/school-quotas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/school-quotas">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/school-quotas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/[skillId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills/[skillId]">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/[skillId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/[skillId]/pathway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills/[skillId]/pathway">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/[skillId]/pathway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/[skillId]/stages/[stageId]/exercise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills/[skillId]/stages/[stageId]/exercise">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/[skillId]/stages/[stageId]/exercise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/associate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills/associate">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/associate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills/new">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/skills">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/stages/[stageId]/shortlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/stages/[stageId]/shortlist">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/stages/[stageId]/shortlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/[id]/zones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/[id]/zones">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/[id]/zones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions/new">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/competitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/competitions">> = Specific
  const handler = {} as typeof import("../../app/admin/competitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/families/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/families">> = Specific
  const handler = {} as typeof import("../../app/admin/families/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/institutions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/institutions">> = Specific
  const handler = {} as typeof import("../../app/admin/institutions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/skills">> = Specific
  const handler = {} as typeof import("../../app/admin/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/[userId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/[userId]">> = Specific
  const handler = {} as typeof import("../../app/admin/users/[userId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users/new">> = Specific
  const handler = {} as typeof import("../../app/admin/users/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitions/[competitionId]/enter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitions/[competitionId]/enter">> = Specific
  const handler = {} as typeof import("../../app/competitions/[competitionId]/enter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitions/[competitionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitions/[competitionId]">> = Specific
  const handler = {} as typeof import("../../app/competitions/[competitionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitions/[competitionId]/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitions/[competitionId]/skills">> = Specific
  const handler = {} as typeof import("../../app/competitions/[competitionId]/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitions">> = Specific
  const handler = {} as typeof import("../../app/competitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/competitions/[competitionId]/appeals/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]/appeals/new">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/competitions/[competitionId]/appeals/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/competitions/[competitionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/competitions/[competitionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/competitions/[competitionId]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]/results">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/competitions/[competitionId]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/competitions/[competitionId]/stages/[stageId]/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]/stages/[stageId]/submit">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/competitions/[competitionId]/stages/[stageId]/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/competitors/[competitorId]/consent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitors/[competitorId]/consent">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/competitors/[competitorId]/consent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/dsar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/dsar">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/dsar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/competitions/[competitionId]/register/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]/register/confirmation">> = Specific
  const handler = {} as typeof import("../../app/competitor/competitions/[competitionId]/register/confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/competitions/[competitionId]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/competitor/competitions/[competitionId]/register">> = Specific
  const handler = {} as typeof import("../../app/competitor/competitions/[competitionId]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/consent/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consent/[token]">> = Specific
  const handler = {} as typeof import("../../app/consent/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/directory/[competitionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/directory/[competitionId]">> = Specific
  const handler = {} as typeof import("../../app/directory/[competitionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/directory/[competitionId]/skills/[skillId]/progression/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/directory/[competitionId]/skills/[skillId]/progression">> = Specific
  const handler = {} as typeof import("../../app/directory/[competitionId]/skills/[skillId]/progression/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/directory/competitors/[competitorKey]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/directory/competitors/[competitorKey]">> = Specific
  const handler = {} as typeof import("../../app/directory/competitors/[competitorKey]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/competitions/[competitionId]/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expert/competitions/[competitionId]/queue">> = Specific
  const handler = {} as typeof import("../../app/expert/competitions/[competitionId]/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expert">> = Specific
  const handler = {} as typeof import("../../app/expert/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/submissions/[submissionId]/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expert/submissions/[submissionId]/moderation">> = Specific
  const handler = {} as typeof import("../../app/expert/submissions/[submissionId]/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/submissions/[submissionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expert/submissions/[submissionId]">> = Specific
  const handler = {} as typeof import("../../app/expert/submissions/[submissionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/competitions/[competitionId]/nominations/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions/[competitionId]/nominations/new">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/competitions/[competitionId]/nominations/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/competitions/[competitionId]/nominations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions/[competitionId]/nominations">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/competitions/[competitionId]/nominations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/competitions/[competitionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions/[competitionId]">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/competitions/[competitionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/competitions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/competitions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/competitors/[competitorId]/lifecycle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitors/[competitorId]/lifecycle">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/competitors/[competitorId]/lifecycle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/nominate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/nominate">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/nominate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/competitions/[competitionId]/register/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions/[competitionId]/register/confirmation">> = Specific
  const handler = {} as typeof import("../../app/institution/competitions/[competitionId]/register/confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/competitions/[competitionId]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institution/competitions/[competitionId]/register">> = Specific
  const handler = {} as typeof import("../../app/institution/competitions/[competitionId]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/results/[competitionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results/[competitionId]">> = Specific
  const handler = {} as typeof import("../../app/results/[competitionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/institution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/institution">> = Specific
  const handler = {} as typeof import("../../app/signup/institution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/(portal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/competitor">> = Specific
  const handler = {} as typeof import("../../app/competitor/(portal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/competitor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/competitor">> = Specific
  const handler = {} as typeof import("../../app/competitor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/expert/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/expert">> = Specific
  const handler = {} as typeof import("../../app/expert/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/(portal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/institution">> = Specific
  const handler = {} as typeof import("../../app/institution/(portal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/institution/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/institution">> = Specific
  const handler = {} as typeof import("../../app/institution/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
