var R=require("../../../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/competitor/(portal)/competitions/[competitionId]/stages/[stageId]/submit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0deh0aq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1--1axv.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_competitor_layout_tsx_1e-x7vm._.js")
R.c("server/chunks/ssr/_1cmd3nr._.js")
R.c("server/chunks/ssr/1jjn_competitions_[competitionId]_stages_[stageId]_submit_page_actions_185x1cr.js")
R.m(98760)
module.exports=R.m(98760).exports
