var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/expert/competitions/[competitionId]/queue/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yvoid0._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1_8o490.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_1t9gtz-._.js")
R.c("server/chunks/ssr/1oeh_server_app_expert_competitions_[competitionId]_queue_page_actions_1e3qnux.js")
R.m(99607)
module.exports=R.m(99607).exports
