var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/institution/competitions/[competitionId]/register/confirmation/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_hmx0f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xwfuzh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_kl8he._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ensmzj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/app_institution_layout_tsx_1ql3u_2._.js")
R.c("server/chunks/ssr/1rcw_competitions_[competitionId]_register_confirmation_page_actions_1vgiuye.js")
R.m(73213)
module.exports=R.m(73213).exports
